import { BLOG_ORIGIN } from "@/lib/blog";
import { ResourcePaths } from "@/components/resource-paths";
import Image from "next/image";
import { MarketingProcessVisual } from "@/components/marketing-process-visual";
import type { Metadata } from "next";
import { MarketingFooter } from "@/components/marketing-footer";
import { ArrowUpRight, AudioLines, BookOpen, BriefcaseBusiness, Mail, MessageCircle, Play, Sparkles } from "lucide-react";
import { MarketingNavigation } from "@/components/marketing-navigation";
import "./marketing.css";
export const metadata: Metadata = { alternates: { canonical: BLOG_ORIGIN },
  title: "B2B Influencer Finder | Your AI creator discovery agent",
  description: "Find relevant B2B influencers and creators across LinkedIn, YouTube, podcasts, newsletters, blogs and X. Match them with your strongest content. Join the waitlist.",
};
const channels = [
  [BriefcaseBusiness, "LinkedIn", "Industry experts and professional creators sharing insights with business audiences."],
  [Play, "YouTube", "Creators publishing tutorials, analysis and industry commentary."],
  [AudioLines, "Podcasts", "Hosts and shows exploring the topics your buyers care about."],
  [Mail, "Newsletters", "Specialist writers and publications, including Substack and beehiiv."],
  [BookOpen, "Blogs", "Authors and independent publishers creating useful niche content."],
  [MessageCircle, "X", "Experts and commentators contributing to relevant industry conversations."],
  [MessageCircle, "Reddit", "Knowledgeable contributors sharing advice and leading discussions in relevant industry communities."],
] as const;
function CTA({label="Find influencers for my brand"}:{label?:string}) { return <a className="marketing-cta" href="/sign-up">{label} <ArrowUpRight size={18}/></a>; }
export default function HomePage() {
  return <div className="marketing"><a className="marketing-skip" href="#main">Skip to content</a>
    <MarketingNavigation/>
    <main id="main">
      <section className="marketing-hero marketing-wrap"><div className="marketing-eyebrow"><span/> Your AI agent for B2B influencer discovery</div><h1>Find the right B2B influencers.<br/><em>And give them something<br/>worth talking about.</em></h1><p className="marketing-intro">Find relevant B2B creators and match them with your strongest content, so industry experts can add their perspective, cite your brand and put you in front of the people and AI systems that matter. Give your AI visibility a boost!</p><CTA/><p className="marketing-fine">Starting at $80/month · Cancel anytime<br/>Join the waitlist for early access.</p><div className="marketing-channel-strip"><span>Find your people on</span><strong>LinkedIn</strong><strong>YouTube</strong><strong>Podcasts</strong><strong>Newsletters</strong><strong>Blogs</strong><strong>X</strong></div></section>
      <section className="marketing-story marketing-wrap" aria-labelledby="advocate-title">
        <div className="advocate-copy"><span className="marketing-eyebrow">Small audiences. Real influence.</span><h2 id="advocate-title">Your next brand advocate probably isn’t a <em>celebrity influencer.</em></h2><p>B2B Influencer Finder searches for credible people already talking about your industry, your customers and the problems you solve.</p><p>Then we figure out what you could actually collaborate on.</p></div>
        <div className="advocate-examples"><div className="advocate-grid">
          <article className="advocate-card advocate-linkedin"><span className="advocate-channel"><BriefcaseBusiness size={17} aria-hidden="true"/> LinkedIn</span><strong className="advocate-number">8,000<span>followers</span></strong><p>They might have a small following in exactly your niche.</p></article>
          <article className="advocate-card"><span className="advocate-channel"><Mail size={17} aria-hidden="true"/> Newsletter</span><h3>In the right<br/>inboxes.</h3><p>Read by exactly the people you sell to.</p></article>
          <article className="advocate-card"><span className="advocate-channel"><Play size={17} aria-hidden="true"/> YouTube</span><h3>On your buyers’<br/>watchlist.</h3><p>A niche channel your customers already watch.</p></article>
          <article className="advocate-card"><span className="advocate-channel"><AudioLines size={17} aria-hidden="true"/> Podcast</span><h3>Part of their<br/>weekly listen.</h3><p>A show that gets your industry talking.</p></article>
        </div><div className="advocate-takeaway"><span>For B2B brands</span><strong>Relevance <span aria-label="matters more than">&gt;</span> reach.</strong></div></div>
      </section>
      <section id="how-it-works" className="marketing-flow marketing-wrap"><header><span className="marketing-eyebrow">From your brand to your next partnership</span><h2>We match people<br/><em>with ideas.</em></h2><p>Your expertise. Their audience. A clear reason to collaborate.</p></header><ol className="marketing-flow-grid">{[
        ["Your brand","Tell us your website and the industries you want to reach.","Your website + target industries"],
        ["Your best content","We find the case studies, research and insights worth talking about.","Your strongest content assets"],
        ["Relevant influencers","We search for people already publishing about your niche.","Creators across six channels"],
        ["The match","See who fits, why they fit and what you could create together.","Evidence + a collaboration idea"],
      ].map(([title,body,result],i)=><li key={title}><div className="marketing-flow-number"><span>0{i+1}</span><span aria-hidden="true">→</span></div>{i===2?<Image className="marketing-flow-photo" src="/photos/creator.webp" alt="Illustrative expert recording a podcast" width={1200} height={800} sizes="(max-width:640px) 90vw, (max-width:1000px) 40vw, 280px"/>:<MarketingProcessVisual kind={i===0?"brand":i===1?"content":"match"}/>} <h3>{title}</h3><p>{body}</p><div className="marketing-flow-result">{result}</div></li>)}</ol><div className="marketing-flow-end"><span aria-hidden="true">✓</span> You review the matches and approve the people you want to work with.</div></section>
      <section className="marketing-example marketing-wrap"><div className="marketing-section-copy"><span className="marketing-eyebrow">An example of a useful match</span><h2>Imagine you’re<br/><em>a fintech company.</em></h2><p>You have a case study showing how customers using referrals have a 35% higher retention rate.</p><p>We find a fintech creator with 14,000 followers who regularly writes about customer acquisition and recently published a post about rising CAC for neobanks.</p><p>That’s a useful match.</p><p>Not just another name in a database.</p></div><div className="marketing-match"><div className="marketing-match-top"><span><Sparkles size={16}/> THE MATCH</span><span>Illustrative match</span></div><div className="marketing-person"><span className="marketing-avatar"><Mail size={26}/></span><div><small>CREATOR</small><h3>Sarah Example</h3><p>14.2K followers · LinkedIn</p><p>Fintech growth & acquisition</p></div></div><div className="marketing-connection"><span/> Matched with your content <span/></div><div className="marketing-asset"><span>YOUR CONTENT</span><h3>Neobank Referral Benchmark Report</h3></div><div className="marketing-match-detail"><h4>Why she matches</h4><p>Sarah regularly covers fintech acquisition strategies and has recently discussed the rising cost of paid customer acquisition.</p><h4>Suggested collaboration</h4><p><em>Are neobanks overlooking their cheapest acquisition channel?</em></p><p>Use your referral benchmark data as the basis for an article exploring referral acquisition versus paid acquisition in fintech.</p></div><div className="marketing-demo-decisions"><span>Approve creator</span><span>Pass</span></div><div className="marketing-match-bottom">Fictional creator, audience size and report shown for illustration.</div></div></section>
      <section id="channels" className="marketing-channel-section"><div className="marketing-wrap"><span className="marketing-eyebrow">Across the B2B conversation</span><h2>Find the voices<br/>your buyers follow.</h2><p className="marketing-intro">B2B influence happens across formats. Discover people who teach, explain, analyse and lead conversations in your industry.</p><div className="marketing-channel-grid">{channels.map(([Icon,name,description])=><article key={name}><Icon size={24}/><h3>{name}{name==="Reddit" ? <span>Coming soon</span>:null}</h3><p>{description}</p></article>)}</div><p className="marketing-channel-note">Search a single channel or combine several, with filters appropriate to each.</p></div></section>
      <section className="marketing-fit marketing-wrap"><div className="marketing-fit-intro"><span className="marketing-eyebrow">Relevance first</span><h2>Find the niche voices<br/>your market already trusts.</h2><p>A smaller, relevant audience can be more valuable than a huge following. Here’s what we look for.</p></div><div className="marketing-fit-checks">{[
        ["The right topics","Do they consistently publish about your industry?"],
        ["Real expertise","Does their published work show they know the subject?"],
        ["A reason to collaborate","Does your content give them something useful to discuss?"],
      ].map(([title,body],i)=><article key={title}><span className="marketing-fit-number">0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div><span className="marketing-fit-tick" aria-hidden="true">✓</span></article>)}<p className="marketing-fit-note">Follower count matters. <strong>Fit comes first.</strong></p></div></section>
      <section id="why-now" className="marketing-why marketing-wrap validation-simple">
        <header><h2>AI can learn about your brand<br/><em>from what others say about you.</em></h2><p>Your website is one source. Articles, videos and newsletters by industry experts give buyers and AI systems more information about your brand.</p></header>
        <div className="validation-comparison">
          <article><MarketingProcessVisual kind="content" wide/><span className="validation-label">You publish</span><h3>“Here’s what we know.”</h3><p>You share your research, advice and customer results on your website and company channels.</p></article>
          <article><Image className="validation-photo" src="/photos/creator.webp" alt="Illustrative industry expert sharing ideas on a podcast" width={1200} height={800} sizes="(max-width:700px) 90vw, 550px"/><span className="validation-label">An industry expert adds</span><h3>“Here’s why it matters.”</h3><p>They discuss your findings in their own words, add their analysis and credit your brand as the source.</p></article>
        </div>
        <footer><h3>We help you find those experts.</h3><p>Match your best content with relevant creators who could turn it into an article, video or newsletter.</p><small>Expert coverage can help people and AI discover your brand. It doesn’t guarantee an AI recommendation.</small></footer>
      </section>
      <section id="plans" className="marketing-section marketing-wrap"><span className="marketing-eyebrow">Choose your approach · Early access plans</span><h2>Run it yourself.<br/>Or get hands-on help from our team.</h2><div className="marketing-plan-grid">{[
        {name:"Finder",type:"Software only",price:"80",description:"Use the software to find and shortlist creators. You handle outreach and manage the partnerships.",features:["B2B influencer discovery","LinkedIn, YouTube, podcasts, newsletters, blogs & X","Website and content analysis","Creator-to-content matching","Collaboration ideas","Match evidence","Approve / reject workflow","Creator shortlist"],cta:"Start finding influencers"},
        {name:"Managed",type:"Software + human to help you with outreach and bookings.",price:"800",description:"Get the software plus a real team to review matches, contact creators and follow up for you.",features:["Everything in Finder","Human-reviewed matches","Personalized creator outreach","Follow-ups","Response management","Collaboration support"],cta:"Get managed outreach"},
      ].map(plan=><article className="marketing-plan" key={plan.name}><h3>{plan.name}</h3><span className="marketing-plan-type">{plan.type}</span><p className="marketing-price"><strong>${plan.price}</strong> /month</p><p>{plan.description}</p><ul>{plan.features.map(feature=><li key={feature}>{feature}</li>)}</ul>{plan.name==="Managed"?<p className="marketing-fine">You approve who we contact. We handle outreach. Fees charged by creators are separate.</p>:null}<CTA label={plan.cta}/></article>)}</div></section>
      <section id="built-for-b2b" className="marketing-audiences marketing-wrap" aria-labelledby="b2b-title">
        <div className="b2b-intro"><span className="marketing-eyebrow">Specialist markets. Specific audiences.</span><h2 id="b2b-title">Built for <em>B2B.</em></h2><p>Find the voices that understand your industry — and the people you sell to.</p></div>
        <ul className="b2b-industries">{["B2B SaaS Companies", "B2B Financial Services", "B2B Agencies", "B2B Professional Services", "B2B Sales Teams", "B2B HR Companies", "B2B Marketers", "Specialist B2B Industries"].map((industry, index) => <li key={industry}><span className="b2b-industry-number" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span><span>{industry}</span></li>)}</ul>
        <div className="b2b-principle"><span className="b2b-principle-label">The audience that matters</span><p>The right <strong>10,00</strong> people.<br/><span>More valuable than the wrong million.</span></p><Image className="b2b-principle-photo" src="/photos/audience.webp" alt="Illustrative small group of professionals engaged in an industry workshop" width={1200} height={800} sizes="(max-width:800px) 90vw, 320px"/></div>
      </section>
      <section id="waitlist" className="marketing-waitlist"><div className="marketing-wrap"><div><span className="marketing-eyebrow">Get early access</span><h2>Get your expertise into<br/><em>the industry conversation.</em></h2><p>Find relevant B2B influencers who can bring their own perspective to your strongest ideas—and introduce your expertise to a wider audience.</p></div><div><CTA label="Find my B2B influencers"/><p className="marketing-fine">Starting at $80/month. Join the waitlist for early access.</p></div></div></section>
    <div className="marketing-wrap"><ResourcePaths/></div></main><MarketingFooter/>
  </div>;
}
