"use client";

import Link from "next/link";
import { WorkspacePanel } from "@/components/workspace-ui";
import { useActionState } from "react";
import { BookOpenText, ExternalLink, Link2 } from "lucide-react";
import { addPublication, type OutcomeActionState } from "@/app/app/brands/outcome-actions";
import type { OutcomeCandidate, PublicationRecord } from "@/lib/outcomes";

const initialState: OutcomeActionState = {};

export function PublicationWorkspace({ brandSlug, candidates, publications, migrationRequired }: { brandSlug: string; candidates: OutcomeCandidate[]; publications: PublicationRecord[]; migrationRequired: boolean }) {
  const [state, action, pending] = useActionState(addPublication, initialState);
  const live = publications.filter((item) => item.verificationStatus === "live").length;
  const linked = publications.filter((item) => item.brandLinkStatus === "present").length;
  const indexed = publications.filter((item) => item.indexStatus === "indexed").length;
  return <main className="page publications-page"><div className="page-header"><div className="page-header-copy"><div className="eyebrow">Outcome evidence</div><h1>Published evidence</h1><p>Save published creator content and track its links and verification.</p></div></div>
    {migrationRequired ? <div className="surface migration-card"><BookOpenText /><div><strong>Slice 5 database update required</strong><p>Run <code>202609260008_outcome_tracking.sql</code>, then refresh.</p></div></div> : <>
      <section className="outcome-metrics"><div><span>Publications</span><strong>{publications.length}</strong></div><div><span>Verified live</span><strong>{live}</strong></div><div><span>Brand link present</span><strong>{linked}</strong></div><div><span>Indexed</span><strong>{indexed}</strong></div></section>
      <WorkspacePanel title="Record a publication" description="Add a public link and its creator match"><div className="outcome-section-head"><div><span className="eyebrow">Add proof</span><h2>Record a publication</h2></div><Link href={`/app/brands/${brandSlug}/outreach`}>View outreach pipeline</Link></div>
        {candidates.length ? <form action={action} className="outcome-form"><input type="hidden" name="brandSlug" value={brandSlug} /><label className="form-full"><span>Creator and matched asset</span><select name="matchId" required defaultValue=""><option value="" disabled>Select an approved match…</option>{candidates.map((item) => <option value={item.matchId} key={item.matchId}>{item.creatorName} — {item.assetTitle}</option>)}</select></label><label><span>Publication title</span><input name="title" required /></label><label><span>Public URL</span><input name="url" type="url" placeholder="https://…" required /></label><label><span>Channel</span><select name="channel" defaultValue="linkedin"><option value="linkedin">LinkedIn</option><option value="newsletter">Newsletter</option><option value="website">Website</option><option value="podcast">Podcast</option><option value="youtube">YouTube</option><option value="industry_publication">Industry publication</option><option value="other">Other</option></select></label><label><span>Format</span><input name="format" placeholder="Post, article, interview…" /></label><label><span>Published date</span><input name="publishedAt" type="date" required /></label><label><span>Brand link</span><select name="brandLinkStatus" defaultValue="present"><option value="present">Present</option><option value="missing">Missing</option><option value="unknown">Unknown</option></select></label><label><span>Disclosure</span><select name="disclosureStatus" defaultValue="disclosed"><option value="disclosed">Disclosed</option><option value="not_required">Not required</option><option value="missing">Missing</option><option value="unknown">Unknown</option></select></label><label><span>Verification</span><select name="verificationStatus" defaultValue="live"><option value="live">Live</option><option value="unverified">Unverified</option><option value="broken">Broken link</option><option value="removed">Removed</option></select></label><label><span>Index status</span><select name="indexStatus" defaultValue="not_checked"><option value="not_checked">Not checked</option><option value="indexed">Indexed</option><option value="not_indexed">Not indexed</option><option value="blocked">Blocked</option></select></label><label className="form-full"><span>Outcome notes</span><textarea name="outcomeNotes" placeholder="What was published, how the expert reframed it, and any early response." /></label><div className="form-full outcome-form-actions">{state.error ? <p className="action-error">{state.error}</p> : null}{state.success ? <p className="action-success">{state.success}</p> : null}<button className="primary-button" disabled={pending}>{pending ? "Saving…" : "Record publication"}</button></div></form> : <div className="outcome-inline-empty"><p>Approve a creator–asset match before recording a publication.</p><Link href={`/app/brands/${brandSlug}/creators`}>Review matches</Link></div>}
      </WorkspacePanel>
      <div className="section-heading"><h2>Publication library</h2><span>{publications.length} saved</span></div>
      {publications.length ? <section className="surface publication-table-wrap"><table className="publication-table"><thead><tr><th>Publication</th><th>Creator</th><th>Matched evidence</th><th>Published</th><th>Proof</th><th>Visibility</th><th /></tr></thead><tbody>{publications.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><span>{item.channel.replaceAll("_", " ")}{item.format ? ` · ${item.format}` : ""}</span></td><td>{item.creatorName}</td><td><strong>{item.assetTitle}</strong><span>{item.question}</span></td><td>{new Date(`${item.publishedAt}T12:00:00`).toLocaleDateString()}</td><td><span className={`status-pill ${item.verificationStatus === "live" ? "eligible" : ""}`}>{item.verificationStatus}</span><small>{item.brandLinkStatus === "present" ? "Brand link present" : `Brand link ${item.brandLinkStatus}`}</small></td><td><span className="status-pill">{item.indexStatus.replaceAll("_", " ")}</span></td><td><a href={item.url} target="_blank" rel="noreferrer" aria-label={`Open ${item.title}`}><ExternalLink size={15} /></a></td></tr>)}</tbody></table></section> : <section className="surface outcome-empty"><Link2 /><h2>No publication evidence yet</h2><p>Add the first public link when an approved creator’s work goes live.</p></section>}
    </>}
  </main>;
}
