"use client";

import Link from "next/link";
import { WorkspacePanel } from "@/components/workspace-ui";
import { useActionState } from "react";
import { Eye, Info, Sparkles } from "lucide-react";
import { addVisibilityObservation, type OutcomeActionState } from "@/app/app/brands/outcome-actions";
import type { VisibilityObservation } from "@/lib/outcomes";

const initialState: OutcomeActionState = {};

export function VisibilityWorkspace({ brandSlug, observations, questions, migrationRequired, savedPrompts = [] }: { savedPrompts?:string[]; brandSlug: string; observations: VisibilityObservation[]; questions: Array<{ id: string; question: string }>; migrationRequired: boolean }) {
  const [state, action, pending] = useActionState(addVisibilityObservation, initialState);
  const mentioned = observations.filter((item) => item.brandMentioned).length;
  const recommended = observations.filter((item) => item.brandRecommended).length;
  const cited = observations.filter((item) => item.creatorEvidenceCited).length;
  return <main className="page visibility-page"><div className="page-header"><div className="page-header-copy"><div className="eyebrow">Directional observation</div><h1>AI visibility</h1><p>Track how AI answers mention, recommend and cite your brand over time.</p></div></div>
    <p><Link className="secondary-button" href={`/app/brands/${brandSlug}/visibility/questions`}>Questions to track ({savedPrompts.length})</Link></p>
    {migrationRequired ? <div className="surface migration-card"><Eye /><div><strong>Slice 5 database update required</strong><p>Run <code>202609260008_outcome_tracking.sql</code>, then refresh.</p></div></div> : <>
      <section className="outcome-metrics"><div><span>Checks logged</span><strong>{observations.length}</strong></div><div><span>Brand mentioned</span><strong>{mentioned}</strong></div><div><span>Brand recommended</span><strong>{recommended}</strong></div><div><span>Creator evidence cited</span><strong>{cited}</strong></div></section>
      <div className="outcome-note warning"><Info size={17} /><div><strong>Read this directionally</strong><p>Answers vary by model, time, location, account, and prompt. Compare repeated checks over time; do not present correlation as causal attribution.</p></div></div>
      <WorkspacePanel title="Log an AI answer" description="Record a manual check from an answer engine"><div className="outcome-section-head"><div><span className="eyebrow">Manual benchmark</span><h2>Log an answer-engine observation</h2></div></div><form action={action} className="outcome-form"><input type="hidden" name="brandSlug" value={brandSlug} /><label><span>Check name</span><input name="name" placeholder="e.g. September benchmark" /></label><label><span>Answer engine</span><select name="answerEngine" defaultValue="chatgpt"><option value="chatgpt">ChatGPT</option><option value="perplexity">Perplexity</option><option value="google_ai_overviews">Google AI Overviews</option><option value="gemini">Gemini</option><option value="claude">Claude</option><option value="other">Other</option></select></label><label><span>Observed at</span><input name="observedAt" type="datetime-local" /></label><label><span>Saved target question</span><select name="targetQuestionId" defaultValue=""><option value="">Custom / none</option>{questions.map((item) => <option value={item.id} key={item.id}>{item.question}</option>)}</select></label><label className="form-full"><span>Exact question tested</span><datalist id="saved-visibility-prompts">{savedPrompts.map(prompt=><option key={prompt} value={prompt}/>)}</datalist><input list="saved-visibility-prompts" name="questionText" required placeholder={questions[0]?.question || "What is the best…?"} /></label><fieldset className="visibility-checks form-full"><legend>What appeared?</legend><label><input type="checkbox" name="brandMentioned" /> Brand mentioned</label><label><input type="checkbox" name="brandRecommended" /> Brand recommended</label><label><input type="checkbox" name="descriptionAccurate" /> Description accurate</label><label><input type="checkbox" name="creatorEvidenceCited" /> Creator publication/evidence cited</label></fieldset><label className="form-full"><span>Response excerpt</span><textarea name="responseExcerpt" placeholder="Paste only the relevant part of the answer." /></label><label><span>Cited URLs</span><textarea name="citedUrls" placeholder="One URL per line" /></label><label><span>Competitors present</span><textarea name="competitors" placeholder="One name per line" /></label><label className="form-full"><span>Notes</span><textarea name="notes" placeholder="Prompt variations, account/location context, and anything needed to reproduce this check." /></label><div className="form-full outcome-form-actions">{state.error ? <p className="action-error">{state.error}</p> : null}{state.success ? <p className="action-success">{state.success}</p> : null}<button className="primary-button" disabled={pending}>{pending ? "Saving…" : "Save observation"}</button></div></form></WorkspacePanel>
      <div className="section-heading"><h2>Saved observations</h2><span>{observations.length} checks</span></div>
      {observations.length ? <section className="visibility-grid">{observations.map((item) => <article className="surface visibility-card" key={item.id}><header><div><span>{item.answerEngine.replaceAll("_", " ")}</span><strong>{item.benchmarkName}</strong></div><time>{item.observedAt ? new Date(item.observedAt).toLocaleDateString() : "—"}</time></header><h2>{item.question}</h2><div className="visibility-signals"><span className={item.brandMentioned ? "yes" : "no"}>{item.brandMentioned ? "Mentioned" : "Not mentioned"}</span><span className={item.brandRecommended ? "yes" : "no"}>{item.brandRecommended ? "Recommended" : "Not recommended"}</span><span className={item.creatorEvidenceCited ? "yes" : "no"}>{item.creatorEvidenceCited ? "Evidence cited" : "No evidence citation"}</span></div>{item.excerpt ? <blockquote>{item.excerpt}</blockquote> : null}{item.notes ? <p>{item.notes}</p> : null}</article>)}</section> : <section className="surface outcome-empty"><Sparkles /><h2>No visibility observations yet</h2><p>Run the same priority question in an answer engine and record the baseline above.</p></section>}
    </>}
  </main>;
}
