import { ResourcePaths } from "@/components/resource-paths";
import type {Metadata} from 'next';
import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {Fragment} from 'react';
import {BLOG_ORIGIN,getPosts,readingMinutes,headingId,postUrl,articleSchema,type BlogBlock} from '@/lib/blog';
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return getPosts().map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const p=getPosts().find(p=>p.slug===slug);if(!p)return {title:'Article not found'};return {title:`${p.metaTitle||p.title} | B2B Influencer Finder`,description:p.description,alternates:{canonical:postUrl(p)},robots:p.status==='draft'?{index:false,follow:false}:undefined,openGraph:{type:'article',title:p.ogTitle,description:p.ogDescription,url:postUrl(p),images:[{url:`${BLOG_ORIGIN}/blog/${p.hero}`,width:1200,height:630,alt:p.heroAlt}],authors:[p.author],publishedTime:p.publishedAt||undefined,modifiedTime:p.updatedAt},twitter:{card:'summary_large_image',title:p.ogTitle,description:p.ogDescription,images:[`${BLOG_ORIGIN}/blog/${p.hero}`]}};}
function Copy({text}:{text:string}){return <>{text}</>;}
function Sources({block}:{block:BlogBlock}) {
 const internal=block.sources?.filter(s=>s.url.startsWith('/'))||[];
 const external=block.sources?.filter(s=>!s.url.startsWith('/'))||[];
 return <>{external.length>0?<span className="blog-sources"><strong>Sources: </strong>{external.map((s,i)=><Fragment key={s.url}>{i>0?' · ':''}<a href={s.url}>{s.label==='Read the research'?`Research: ${new URL(s.url, BLOG_ORIGIN).hostname.replace('www.','')}`:s.label}</a></Fragment>)}</span>:null}{internal.length>0?<span className="blog-sources"><strong>Further reading: </strong>{internal.map((s,i)=><Fragment key={s.url}>{i>0?' · ':''}<Link href={s.url}>{s.label}</Link></Fragment>)}</span>:null}</>;
}
export default async function ArticlePage({params}:Props){const {slug}=await params;const posts=getPosts();const p=posts.find(p=>p.slug===slug);if(!p)notFound();const headings=p.blocks.filter(b=>b.type==='h2');const diagramSection=p.blocks.findIndex(b=>b.type==='h2'&&b.text===p.diagramAfter);const nextHeading=p.blocks.findIndex((b,i)=>i>diagramSection&&b.type==='h2');const diagramIndex=nextHeading<0?p.blocks.length:nextHeading;
 const breadcrumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{ '@type':'ListItem',position:1,name:'Home',item:BLOG_ORIGIN},{'@type':'ListItem',position:2,name:'Resources',item:`${BLOG_ORIGIN}/blog`},{'@type':'ListItem',position:3,name:p.title,item:postUrl(p)}]};
 const diagram=<figure className="blog-diagram"><Image src={`/blog/${p.diagram}`} width={p.diagramWidth||1200} height={p.diagramHeight||630} alt={p.diagramAlt} sizes="(max-width:800px) 100vw, 760px"/><figcaption>{p.diagramAlt}. An explanatory model, not a guarantee of AI inclusion. <a href={`/blog/${p.diagram}`} target="_blank" rel="noreferrer">View full-size diagram ↗</a></figcaption></figure>;
 return <main id="main" className="marketing-wrap"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([articleSchema(p),breadcrumbs]).replace(/</g,'\\u003c')}}/><nav className="blog-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/blog">Resources</Link><span>/</span><span>{p.category}</span></nav><header className="blog-article-header"><span className="blog-kicker">{p.category} · {readingMinutes(p)} min read</span><h1>{p.title}</h1><p className="blog-deck">{p.description}</p><div className="blog-byline"><span>By {p.author}</span>{p.publishedAt?<span>Published <time dateTime={p.publishedAt}>{p.publishedAt}</time></span>:<span>Draft · Not published</span>}<span>Updated <time dateTime={p.updatedAt}>{p.updatedAt}</time></span></div></header><Image className="blog-article-hero" src={`/blog/${p.hero}`} width={1200} height={630} alt={p.heroAlt} preload sizes="(max-width:1200px) 100vw, 1180px"/>
 <div className="blog-reading-layout"><aside className="blog-toc"><details open><summary>In this guide</summary><nav aria-label="Table of contents">{headings.map(h=><a key={h.text} href={`#${headingId(h.text)}`}>{h.text}</a>)}</nav></details></aside><article className="blog-prose">{p.blocks.map((b,i)=><Fragment key={i}>{i===diagramIndex?diagram:null}{b.type==='h2'?<h2 id={headingId(b.text)}>{b.text}</h2>:b.type==='quote'?<blockquote><Copy text={b.text}/></blockquote>:b.type==='li'?<ul><li><Copy text={b.text}/></li></ul>:<p><Copy text={b.text}/><Sources block={b}/></p>}</Fragment>)}{diagramIndex===p.blocks.length?diagram:null}<div className="blog-article-end"><Link href="/blog">← Back to all resources</Link><a href="#main">Back to top ↑</a></div></article></div>
 <section className="blog-related"><span className="blog-kicker">Keep exploring</span><h2>Read next</h2><div>{posts.filter(other=>other.slug!==slug).sort((a,b)=>{const rank=(s:string)=>{const i=p.relatedArticles?.indexOf(s)??-1;return i<0?999:i;};return rank(a.slug)-rank(b.slug);}).slice(0,3).map(other=><Link key={other.slug} href={`/blog/${other.slug}`}><span>{readingMinutes(other)} min read</span><h3>{other.title}</h3><span>Read the guide ↗</span></Link>)}</div></section><ResourcePaths compact/></main>;
}
